---
- name: Gather facts
  setup:
  register: _facts

- debug: var=_facts

#- name: Update OS
#  apt:
#    upgrade: yes
#    update_cache: yes
#    cache_valid_time: 86400

#- name: Add Docker's official GPG Key
#  shell: bash -lc "curl -fsSL https://download.docker.com/linux/raspbian/gpg | apt-key add -"

- name: Add gpg Key for Docker-Ce repository
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - https://download.docker.com/linux/raspbian/gpg

- name: Delete Docker repository files
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - /etc/apt/sources.list.d/docker.list

- name: Create Docker repository files
  file:
    name: "{{ item }}"
    state: touch
  with_items:
    - /etc/apt/sources.list.d/docker.list

- name: Add Docker repository Info to the list
  lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: "{{ item }}"
  with_items:
    - 'deb [arch=armhf] https://download.docker.com/linux/raspbian stretch stable'
  when: "'stretch' in _facts.ansible_facts.ansible_lsb.description"

#- name: Add repositories stretch
#  shell: bash -lc 'echo "deb [arch=armhf] https://download.docker.com/linux/raspbian stretch stable" | tee /etc/apt/sources.list.d/docker.list'
#  when: "'stretch' in _facts.ansible_facts.ansible_lsb.description"

- name: Update repo Cache
  apt:
    update_cache: yes

- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl 
    - gnupg2 
    - software-properties-common
    - python-pip

- name: Install Docker-CE
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker-ce
  ignore_errors: true
#  register: _changed

- name: Install Python libraries
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker-compose
    - docker-py

- name: Reboot Rp
  #shell: /bin/bash -lc "reboot"
  shell: /bin/bash -lc "sleep 5 && reboot"
  async: 1
  poll: 0
  ignore_errors: true
#  when: _changed is changed

- name: wait for restart
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
#  when: _changed is changed

- name: Test connection after reboot
  ping:

- name: start docker-ce
  systemd:
    name: docker
    state: started
    enabled: yes
