---
- name: Install dependencies (CentOS)
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Add docer-ce repo (CentOS)
  shell: bash -lc "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
  register: _install_docker_repo

- name: Enable edge and test version (CentOS)
  shell: bash -lc "yum-config-manager --enable {{item}}"
  with_items:
    - docker-ce-edge
    - docker-ce-test
  when: _install_docker_repo.rc == 0

- name: Update OS (CentOS)
  yum:
    name: "*"
    state: latest

- name: install docker (CentOS)
  yum:
    name: docker-ce
    state: present

- name: start docker (CentOS)
  systemd: 
    name: docker
    enabled: yes
    state: started
